name: quanttide_hr
description: 量潮人力资源工具包 - QtCloud HR Toolkit
version: 0.1.0
homepage: https://github.com/quanttide/quanttide-hr-toolkit

environment:
  sdk: ^3.11.5

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
